name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: macos-latest
    name: goreleaser
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow Fetch
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
      - name: Add MacOS certs
        run: cp ./ci/add-osx-cert.sh /tmp/add-osx-cert.sh && chmod +x /tmp/add-osx-cert.sh && /tmp/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Install gon via HomeBrew for code signing and app notarization
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
      - name: Set stage to prd for all
        run: |
          echo "::set-env name=STAGE::PRD"
      - name: Set stage to dev if tagged develop
        if: endsWith(github.ref, '-dev')
        run: |
          echo "::set-env name=STAGE::DEV"
      - name: Set secret names
        id: secretnames
        run: |
          echo "::set-output name=SERVICES_API_URL::SERVICES_API_URL_${{env.STAGE}}"
          echo "::set-output name=VAULT_API_URL::VAULT_API_URL_${{env.STAGE}}"
          echo "::set-output name=VAULT_SALT_SECRET::VAULT_SALT_SECRET_${{env.STAGE}}"
          echo "::set-output name=SERVICES_HUB_AUTH_URL::SERVICES_HUB_AUTH_URL_${{env.STAGE}}"
          echo "::set-output name=TXL_HUB_TARGET::TXL_HUB_TARGET_${{env.STAGE}}"
          echo "::set-output name=TXL_HUB_MA::TXL_HUB_MA_${{env.STAGE}}"
          echo "::set-output name=TXL_THREADS_TARGET::TXL_THREADS_TARGET_${{env.STAGE}}"
          echo "::set-output name=TXL_USER_KEY::TXL_USER_KEY_${{env.STAGE}}"
          echo "::set-output name=TXL_USER_SECRET::TXL_USER_SECRET_${{env.STAGE}}"
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MONGO_USR: ${{ secrets.MONGO_USR }}
          MONGO_PW: ${{ secrets.MONGO_PW }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_REPLICA_SET: ${{ secrets.MONGO_REPLICA_SET }}
          SERVICES_API_URL: ${{ secrets[steps.vars.outputs.SERVICES_API_URL] }}
          VAULT_API_URL: ${{ secrets[steps.vars.outputs.VAULT_API_URL] }}
          VAULT_SALT_SECRET: ${{ secrets[steps.vars.outputs.VAULT_SALT_SECRET] }}
          SERVICES_HUB_AUTH_URL: ${{ secrets[steps.vars.outputs.SERVICES_HUB_AUTH_URL] }}
          TXL_HUB_TARGET: ${{ secrets[steps.vars.outputs.TXL_HUB_TARGET] }}
          TXL_HUB_MA: ${{ secrets[steps.vars.outputs.TXL_HUB_MA] }}
          TXL_THREADS_TARGET: ${{ secrets[steps.vars.outputs.TXL_THREADS_TARGET] }}
          TXL_USER_KEY: ${{ secrets[steps.vars.outputs.TXL_USER_KEY] }}
          TXL_USER_SECRET: ${{ secrets[steps.vars.outputs.TXL_USER_SECRET] }}
